const Constants = {
    FONT_FAMILY: 'VT323-Regular',
    WIDTH: 900,
    HEIGHT: 900,
    TILE_SIZE: 30,
    ENEMY_MOVE_DURATION: 1000,
    ROW_PAUSE_PERIOD: 1000,
    MAX_FIRE_ANIMATION_DURATION: 1000,
    MIN_FIRE_ANIMATION_DURATION: 400,
    POPUP_DEPTH: 4,
    HUD_DEPTH: 3,
    AMMUNITION_DEPTH: 2,
    TOWER_DEPTH: 1,
    TOWER_COST: 100,
    KILLED_ENEMY_REWARD: 10,
};

export default Constants;